services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://rental_user:rental_password@db:5432/rental_db
      - ENVIRONMENT=development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=rental_user
      - POSTGRES_PASSWORD=rental_password
      - POSTGRES_DB=rental_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rental_user -d rental_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: