"""Create item_packaging table

Revision ID: 005_create_item_packaging_table
Revises: 004_enhance_customers_table
Create Date: 2025-06-28 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '005_create_item_packaging_table'
down_revision = '004_enhance_customers_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_packaging',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_by', sa.String(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('label', sa.String(length=255), nullable=False),
        sa.Column('unit', sa.String(length=255), nullable=False),
        sa.Column('remarks', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('label')
    )
    op.create_index('packaging_label_idx', 'item_packaging', ['label'], unique=False)
    op.create_index(op.f('ix_item_packaging_id'), 'item_packaging', ['id'], unique=False)
    op.create_index(op.f('ix_item_packaging_label'), 'item_packaging', ['label'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_packaging_label'), table_name='item_packaging')
    op.drop_index(op.f('ix_item_packaging_id'), table_name='item_packaging')
    op.drop_index('packaging_label_idx', table_name='item_packaging')
    op.drop_table('item_packaging')
    # ### end Alembic commands ###
