"""Create unit_of_measurement table

Revision ID: 006_create_unit_of_measurement_table
Revises: 005_create_item_packaging_table
Create Date: 2025-06-28 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '006'
down_revision = '005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_of_measurement',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_by', sa.String(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('abbreviation', sa.String(length=8), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('abbreviation'),
        sa.UniqueConstraint('name')
    )
    op.create_index('uom_abbreviation_idx', 'unit_of_measurement', ['abbreviation'], unique=False)
    op.create_index(op.f('ix_unit_of_measurement_abbreviation'), 'unit_of_measurement', ['abbreviation'], unique=True)
    op.create_index(op.f('ix_unit_of_measurement_id'), 'unit_of_measurement', ['id'], unique=False)
    op.create_index(op.f('ix_unit_of_measurement_name'), 'unit_of_measurement', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_of_measurement_name'), table_name='unit_of_measurement')
    op.drop_index(op.f('ix_unit_of_measurement_id'), table_name='unit_of_measurement')
    op.drop_index(op.f('ix_unit_of_measurement_abbreviation'), table_name='unit_of_measurement')
    op.drop_index('uom_abbreviation_idx', table_name='unit_of_measurement')
    op.drop_table('unit_of_measurement')
    # ### end Alembic commands ###
