"""Create id_managers table

Revision ID: 008_create_id_managers_table
Revises: 007_create_warehouses_table
Create Date: 2025-06-28 11:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '008'
down_revision = '007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('id_managers',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_by', sa.String(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('prefix', sa.String(length=255), nullable=False),
        sa.Column('latest_id', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('prefix')
    )
    op.create_index('id_manager_prefix_idx', 'id_managers', ['prefix'], unique=False)
    op.create_index(op.f('ix_id_managers_id'), 'id_managers', ['id'], unique=False)
    op.create_index(op.f('ix_id_managers_prefix'), 'id_managers', ['prefix'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_id_managers_prefix'), table_name='id_managers')
    op.drop_index(op.f('ix_id_managers_id'), table_name='id_managers')
    op.drop_index('id_manager_prefix_idx', table_name='id_managers')
    op.drop_table('id_managers')
    # ### end Alembic commands ###
