"""Create item categories and subcategories tables

Revision ID: 8e8ec3b7555d
Revises: 36168e2b083f
Create Date: 2025-06-28 14:11:07.155357

"""
from alembic import op
import sqlalchemy as sa


revision = '8e8ec3b7555d'
down_revision = '008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('abbreviation', sa.String(length=9), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_categories_abbreviation'), 'item_categories', ['abbreviation'], unique=True)
    op.create_index(op.f('ix_item_categories_id'), 'item_categories', ['id'], unique=False)
    op.create_index('ix_item_categories_name', 'item_categories', ['name'], unique=False)
    op.create_table('item_subcategories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('abbreviation', sa.String(length=9), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('item_category_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_category_id'], ['item_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'item_category_id', name='unique_subcategory_name_per_category')
    )
    op.create_index('ix_item_subcategories_abbreviation', 'item_subcategories', ['abbreviation'], unique=False)
    op.create_index('ix_item_subcategories_category', 'item_subcategories', ['item_category_id'], unique=False)
    op.create_index(op.f('ix_item_subcategories_id'), 'item_subcategories', ['id'], unique=False)
    op.create_index('ix_item_subcategories_name', 'item_subcategories', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_subcategories_name', table_name='item_subcategories')
    op.drop_index(op.f('ix_item_subcategories_id'), table_name='item_subcategories')
    op.drop_index('ix_item_subcategories_category', table_name='item_subcategories')
    op.drop_index('ix_item_subcategories_abbreviation', table_name='item_subcategories')
    op.drop_table('item_subcategories')
    op.drop_index('ix_item_categories_name', table_name='item_categories')
    op.drop_index(op.f('ix_item_categories_id'), table_name='item_categories')
    op.drop_index(op.f('ix_item_categories_abbreviation'), table_name='item_categories')
    op.drop_table('item_categories')
    # ### end Alembic commands ###